enum status {
  no_response
  answered
  refunded
}

enum interaction_type {
  full
  half
  solo
}

enum role {
  admin
  user
  testsolver
}

enum solve_type {
  guess
  answer_token
}

enum unlock_type {
  guess
}

table bph_site_answer_token {
  id serial [pk, not null, increment]
  team_id varchar [not null]
  event_id varchar [not null]
  timestamp "timestamp with time zone" [not null, default: `now()`]
  puzzle_id varchar
}

table bph_site_erratum {
  id serial [pk, not null, increment]
  puzzle_id varchar [not null]
  timestamp "timestamp with time zone" [not null, default: `now()`]
  description text [not null]

  indexes {
    puzzle_id [name: 'errata_puzzle_idx']
  }
}

table bph_site_event {
  id varchar(255) [pk, not null]
  name varchar(255) [not null]
  answer varchar(255) [not null]
  start_time "timestamp with time zone" [not null]
  description text [not null]
}

table bph_site_feedback {
  id serial [pk, not null, increment]
  team_id varchar [not null]
  timestamp "timestamp with time zone" [not null, default: `now()`]
  feedback text [not null]
}

table bph_site_follow_up {
  id serial [pk, not null, increment]
  hint_id serial [not null, increment]
  user_id varchar [not null]
  message text [not null]
  time "timestamp with time zone" [not null, default: `now()`]

  indexes {
    hint_id [name: 'hint_idx']
  }
}

table bph_site_guess {
  id serial [pk, not null, increment]
  puzzle_id varchar [not null]
  team_id varchar [not null]
  guess varchar(255) [not null]
  is_correct boolean [not null]
  submit_time "timestamp with time zone" [not null, default: `now()`]

  indexes {
    (team_id, puzzle_id) [name: 'guesses_team_and_puzzle_idx']
  }
}

table bph_site_hint {
  id serial [pk, not null, increment]
  puzzle_id varchar [not null]
  team_id varchar [not null]
  request text [not null]
  request_time "timestamp with time zone" [not null, default: `now()`]
  claimer varchar
  claim_time "timestamp with time zone"
  response text
  response_time "timestamp with time zone"
  status status [not null, default: 'no_response']

  indexes {
    (team_id, puzzle_id) [name: 'hints_team_and_puzzle_idx']
  }
}

table bph_site_puzzle {
  id varchar(255) [pk, not null]
  name varchar(255) [not null]
  answer varchar(255) [not null]
}

table bph_site_solve {
  id serial [pk, not null, increment]
  puzzle_id varchar [not null]
  team_id varchar [not null]
  solve_time "timestamp with time zone" [not null, default: `now()`]
  type solve_type [not null, default: 'guess']

  indexes {
    (team_id, puzzle_id) [name: 'solves_team_puzzle_idx']
  }
}

table bph_site_team {
  id varchar(255) [pk, not null]
  display_name varchar(255) [not null]
  password varchar(255) [not null]
  role role [not null, default: 'user']
  members text [not null, default: '[]']
  interaction_type interaction_type [not null]
  create_time "timestamp with time zone" [not null, default: `now()`]
  finish_time "timestamp with time zone"
}

table bph_site_unlock {
  id serial [pk, not null, increment]
  puzzle_id varchar [not null]
  team_id varchar [not null]
  unlock_time "timestamp with time zone" [not null, default: `now()`]
  type unlock_type [not null, default: 'guess']

  indexes {
    (team_id, puzzle_id) [name: 'unlocks_team_puzzle_idx']
    (team_id, puzzle_id) [name: 'team_and_puzzle', unique]
  }
}

ref: bph_site_answer_token.team_id > bph_site_team.id

ref: bph_site_answer_token.event_id > bph_site_event.id

ref: bph_site_answer_token.puzzle_id > bph_site_puzzle.id

ref: bph_site_erratum.puzzle_id > bph_site_puzzle.id

ref: bph_site_follow_up.hint_id > bph_site_hint.id

ref: bph_site_follow_up.user_id - bph_site_team.id

ref: bph_site_guess.team_id > bph_site_team.id

ref: bph_site_guess.puzzle_id > bph_site_puzzle.id

ref: bph_site_hint.team_id > bph_site_team.id

ref: bph_site_hint.puzzle_id > bph_site_puzzle.id

ref: bph_site_hint.claimer > bph_site_team.id

ref: bph_site_solve.team_id > bph_site_team.id

ref: bph_site_solve.puzzle_id > bph_site_puzzle.id

ref: bph_site_unlock.team_id > bph_site_team.id

ref: bph_site_unlock.puzzle_id > bph_site_puzzle.id
